=== TeoG-H/proiect-PW/continut/resurse/persoane.dtd
<!ELEMENT persoane (persoana+)>   <!-- pers+  cel putin o pers, una sau mai multe  --> 

<!ELEMENT persoana (nume, prenume, adresa, perioada_activitate, functie, an_nastere, an_deces)>  <!-- struct unei pers, daca le pui in alta ordine nu merge-->
<!ATTLIST persoana id NMTOKEN #REQUIRED> <!-- required - ca e obligatoriu, NMT... text simplu fara spatii(1, p1), se poate folosi si ID in loc de NMT.. dar nu poate incepe cu cifra  -->

<!ELEMENT nume (#PCDATA)>  <!-- PCDATA - text simplu -->
<!ELEMENT prenume (#PCDATA)>

<!ELEMENT adresa (strada, numar, localitate, judet, tara)>
<!ELEMENT strada (#PCDATA)>
<!ELEMENT numar (#PCDATA)>
<!ELEMENT localitate (#PCDATA)>
<!ELEMENT judet (#PCDATA)>
<!ELEMENT tara (#PCDATA)>

<!ELEMENT perioada_activitate (inceput, sfarsit)>
<!ELEMENT inceput (#PCDATA)>
<!ELEMENT sfarsit (#PCDATA)>

<!ELEMENT functie (#PCDATA)>
<!ELEMENT an_nastere (#PCDATA)>
<!ELEMENT an_deces (#PCDATA)>

=== TeoG-H/proiect-PW/continut/resurse/persoane.xml
<?xml version="1.0" encoding="UTF-8"?>              <!--  documentul este in format xml, are versiunea 1.0 si e encodat.. cu diacritice-->
<!DOCTYPE persoane SYSTEM "persoane.dtd">           <!-- leaga xml de dtd adica structura acestui xml este def in dtd, SYSTEM-dtd in fisier local-->
<persoane>
    <persoana id="1">
        <nume>Heineken</nume>
        <prenume>Gerard Adriaan</prenume>
        <adresa>
            <strada>Nieuwezijds Voorburgwal</strada>
            <numar>42</numar>
            <localitate>Amsterdam</localitate>
            <judet>Noord-Holland</judet>
            <tara>Olanda</tara>
        </adresa>
        <perioada_activitate>
            <inceput>1873</inceput>
            <sfarsit>1900</sfarsit>
        </perioada_activitate>
        <functie>Fondator</functie>
        <an_nastere>1841</an_nastere>
        <an_deces>1893</an_deces>
    </persoana>

    <persoana id="2">
        <nume>Heineken</nume>
        <prenume>Henry Pierre</prenume>
        <adresa>
            <strada>Tweede Weteringplantsoen</strada>
            <numar>21</numar>
            <localitate>Amsterdam</localitate>
            <judet>Noord-Holland</judet>
            <tara>Olanda</tara>
        </adresa>
        <perioada_activitate>
            <inceput>1917</inceput>
            <sfarsit>1940</sfarsit>
        </perioada_activitate>
        <functie>CEO 1917–1940</functie>
        <an_nastere>1886</an_nastere>
        <an_deces>1942</an_deces>
    </persoana>

    <persoana id="3">
        <nume>Heineken</nume>
        <prenume>Alfred Henry</prenume>
        <adresa>
            <strada>Herengracht</strada>
            <numar>90</numar>
            <localitate>Amsterdam</localitate>
            <judet>Noord-Holland</judet>
            <tara>Olanda</tara>
        </adresa>
        <perioada_activitate>
            <inceput>1971</inceput>
            <sfarsit>1989</sfarsit>
        </perioada_activitate>
        <functie>CEO 1971–1989</functie>
        <an_nastere>1923</an_nastere>
        <an_deces>2002</an_deces>
    </persoana>

    <persoana id="4">
        <nume>van Boxmeer</nume>
        <prenume>Jean-François</prenume>
        <adresa>
            <strada>Tweede Weteringplantsoen</strada>
            <numar>21</numar>
            <localitate>Amsterdam</localitate>
            <judet>Noord-Holland</judet>
            <tara>Olanda</tara>
        </adresa>
        <perioada_activitate>
            <inceput>2005</inceput>
            <sfarsit>2020</sfarsit>
        </perioada_activitate>
        <functie>CEO 2005–2020</functie>
        <an_nastere>1961</an_nastere>
        <an_deces>-</an_deces>
    </persoana>

    <persoana id="5">
        <nume>Friese</nume>
        <prenume>Dolf van den</prenume>
        <adresa>
            <strada>Tweede Weteringplantsoen</strada>
            <numar>21</numar>
            <localitate>Amsterdam</localitate>
            <judet>Noord-Holland</judet>
            <tara>Olanda</tara>
        </adresa>
        <perioada_activitate>
            <inceput>2020</inceput>
            <sfarsit>prezent</sfarsit>
        </perioada_activitate>
        <functie>CEO 2020–prezent</functie>
        <an_nastere>1968</an_nastere>
        <an_deces>-</an_deces>
    </persoana>
</persoane>
